### ISSUE TITLE
Options does not appear in the top right hand corner on custom screen

### ISSUE THREAD

**Issue by DanielTB80** [dakboard/Hardware-OS#189] opened 2024-12-15 04:27 UTC
**Describe the bug**

On a custom screen, specifically on "Big Calendar", the "Options" menu does not appear in the top right hand corner as it does in the "My Predefined Screen".

**To Reproduce**

Use Custom Screen "Big Calendar"

**Expected behavior**

I should be able to navigate to the Dakboard options and website from the "Option" button.

**Screenshots**

**Device Type (please complete the following information):**
- DAKboard CPU 4

**DAKboard OS Version (please complete the following information): 4.01
 If known, please include the DAKboard OS version.

**Additional context**

**Comment by cocarrig** [comment] 2024-12-18 15:13
Hi @DanielTB80,

The gear will display under 2 conditions by design:
- Always when viewed with the predefined screen, since this is often used for android app uses (the app is no longer available for use officially though).
- On custom screens when an active login session is present on the device.

Since you indicated this is on a custom screen, we would not expect the gear to show.  If you would like a link to the login or another page on dakboard.com of another location, you can add it via a button block easily if desired:
https://blog.dakboard.com/qr-codes-buttons-and-calendar-style-updates/

For now we will close this case, but reach back out if you have any other issues.

**Closed by cocarrig** 2024-12-18 15:13 UTC
Labels: bug
